eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-server: true
    service-url: 
      defaultZone: http://localhost:8761/eureka
spring: 
  application:
    name: CONFIG-DEV
